services:
  playwright-vnc:
    image: ghcr.io/elzx66/playwright_python_vnc:latest
    container_name: playwright-vnc
    network_mode: bridge
    ports:
      - "5991:5900"
    environment:
      - USER_DATA_DIR=/app/user_data
      - SHARED_DIR=/shared
      - SCREEN_RES=1280x1024x24
      - DISPLAY=:99
    volumes:
      - ./shared:/shared
      - ./user_data:/app/user_data
    user: "0:0"
    tty: true
    stdin_open: true
    # 注释：若需容器常驻，可取消下方 command 注释（tail -f /dev/null 防止容器退出）
    # command: tail -f /dev/null    
    restart: no
    privileged: false