services:
  playwright-vnc:
    build:
      context: .
      args:
        HTTPS_PROXY: http://192.168.10.223:20172
    container_name: playwright-vnc-test
    network_mode: bridge
    ports:
      - "5991:5900"
    environment:
      - USER_DATA_DIR=/app/user_data
    volumes:
      - ./shared:/shared
      - ./user_data:/app/user_data
    user: "0:0"
    tty: true
    stdin_open: true
    # 注释：若需容器常驻，可取消下方 command 注释（tail -f /dev/null 防止容器退出）
    # command: tail -f /dev/null    
    restart: no
    privileged: false